// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eobnuchqwpchzidyrkpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvYm51Y2hxd3BjaHppZHlya3B2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDE4OTcsImV4cCI6MjA2NDExNzg5N30.ZU2puvEmeqZ8dxnwFuA8GMccPZDhO7fhYYUYp9J3TV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);